In [1]:
import numpy as np

## Creating Numpy Array from Python Lists

In [2]:
np.array([1, 3, 5, 7, 9])

array([1, 3, 5, 7, 9])

In [3]:
np.array([3.14, 5, 2, 10])

array([ 3.14,  5.  ,  2.  , 10.  ])

In [4]:
np.array([2, 4, 6, 8], dtype = 'float32')

array([2., 4., 6., 8.], dtype=float32)

In [5]:
array_one = np.array([1, 3, 5, 7])
type(array_one)

numpy.ndarray

In [6]:
array_two = np.array([[1, 3, 5],
                     [2, 4, 6]])
type(array_two)

numpy.ndarray

In [7]:
array_two.shape

(2, 3)

In [8]:
array_two.ndim

2

In [9]:
array_two.size

6

## Creating Numpy Array from Scratch

In [10]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.ones([3, 10], dtype = int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [12]:
np.full((3, 5), 8.9)

array([[8.9, 8.9, 8.9, 8.9, 8.9],
       [8.9, 8.9, 8.9, 8.9, 8.9],
       [8.9, 8.9, 8.9, 8.9, 8.9]])

In [13]:
np.linspace(0, 1 ,9)

array([0.   , 0.125, 0.25 , 0.375, 0.5  , 0.625, 0.75 , 0.875, 1.   ])

In [14]:
np.random.seed(0)
np.random.random([4, 4])

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ]])

In [15]:
np.random.normal(0, 1, (3, 3))

array([[ 0.44386323,  0.33367433,  1.49407907],
       [-0.20515826,  0.3130677 , -0.85409574],
       [-2.55298982,  0.6536186 ,  0.8644362 ]])

In [16]:
np.full((3, 5), 10)

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [17]:
np.random.randint(0, 10, (5, 5))

array([[7, 2, 0, 0, 4],
       [5, 5, 6, 8, 4],
       [1, 4, 9, 8, 1],
       [1, 7, 9, 9, 3],
       [6, 7, 2, 0, 3]])

## Indexing and Slicing

### One Dimensional Subarray

In [18]:
x1 = np.random.randint(20, size = 6)

In [19]:
x1

array([12, 10, 11,  4,  6,  4])

In [20]:
x1[4], x1[0], x1[-1]

(6, 12, 4)

### Multi - Dimensional Array

In [21]:
x2 = np.random.randint(10, size = (4, 4))

In [22]:
x2

array([[4, 3, 4, 4],
       [8, 4, 3, 7],
       [5, 5, 0, 1],
       [5, 9, 3, 0]])

In [23]:
x2[2, 2]

0

In [24]:
	x2[2, 2] = 10

In [25]:
x2

array([[ 4,  3,  4,  4],
       [ 8,  4,  3,  7],
       [ 5,  5, 10,  1],
       [ 5,  9,  3,  0]])

### Slicing

In [26]:
x1

array([12, 10, 11,  4,  6,  4])

In [27]:
x1[0:3]

array([12, 10, 11])

In [28]:
x1[::3]

array([12,  4])

In [29]:
x2

array([[ 4,  3,  4,  4],
       [ 8,  4,  3,  7],
       [ 5,  5, 10,  1],
       [ 5,  9,  3,  0]])

In [30]:
x2[:2, :3]

array([[4, 3, 4],
       [8, 4, 3]])

In [31]:
x2[:, :2]

array([[4, 3],
       [8, 4],
       [5, 5],
       [5, 9]])

## Reshaping array and Transpose

In [32]:
grid = np.arange(1, 10)
grid.shape

(9,)

In [33]:
grid.reshape((3, 3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Array Concatenation and Splitting

In [34]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

In [35]:
np.concatenate((x, y))

array([1, 2, 3, 4, 5, 6])

In [36]:
grid = np.array([[1, 4, 6], [2,4,8]])
grid

array([[1, 4, 6],
       [2, 4, 8]])

In [37]:
np.concatenate((grid, grid)) # axis = 0 by default

array([[1, 4, 6],
       [2, 4, 8],
       [1, 4, 6],
       [2, 4, 8]])

In [38]:
np.vstack((x, grid))

array([[1, 2, 3],
       [1, 4, 6],
       [2, 4, 8]])

In [39]:
y = np.array([[99], [99]])
np.hstack((y, grid))

array([[99,  1,  4,  6],
       [99,  2,  4,  8]])

## Splitting Arrays

In [40]:
array = np.array([1, 2, 4, 6, 7, 9])

In [41]:
x1, x2, x3 = np.split(array, [2, 4])

In [42]:
x1

array([1, 2])

In [43]:
x2

array([4, 6])

In [44]:
x3

array([7, 9])

## Broadcasting and Vetocrized operations

In [45]:
a = np.arange(3)

In [46]:
a

array([0, 1, 2])

In [47]:
# broadcasting 
a + 3

array([3, 4, 5])

In [48]:
b = np.ones((3, 3), dtype = int)

In [49]:
b

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [50]:
a + b

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [51]:
a * b

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [52]:
c = np.arange(3).reshape((3, 1))

In [53]:
c

array([[0],
       [1],
       [2]])

## Manipulating and Comparing Arrays

In [54]:
list_number = [2, 4, 6, 8]

In [55]:
np.array(list_number)

array([2, 4, 6, 8])

In [56]:
sum(list_number)

20

In [57]:
np.sum(list_number)

20

In [58]:
# Create massive numpy arrays
massive_array = np.random.random(10000)
massive_array[:5]
massive_array.shape

(10000,)

In [59]:
%timeit sum(massive_array)
%timeit np.sum(massive_array)

4.06 ms ± 461 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
36.4 µs ± 7.16 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [60]:
np.mean(massive_array)

0.5013864005396481

In [61]:
np.min(massive_array)

2.0027530115096503e-05

In [62]:
np.max(massive_array)

0.9999709462497284

In [63]:
dog_height = [600, 470, 170, 430, 300]

In [64]:
np.array(dog_height)

array([600, 470, 170, 430, 300])

In [65]:
np.std(dog_height)

147.32277488562318

In [66]:
np.var(dog_height)

21704.0

## Sorting Arrays

In [67]:
x= np.array([1,4,3,7,6,2])
np.sort(x)


array([1, 2, 3, 4, 6, 7])

In [68]:
np.argsort(x)

array([0, 5, 2, 1, 4, 3], dtype=int64)

## Sorting along rows and columns

In [69]:
np.random.seed(42)
MatA = np.random.randint(0, 10, size = (4, 6))

In [70]:
MatA

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [71]:
np.sort(MatA, axis = 0) # sort columns

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

In [72]:
np.sort(MatA, axis = 1) # sort rows

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])

## Linear Algebra

In [73]:
A = np.array([[1, 2, 3], [5, 6, 7], [9, 10, 11]])

In [74]:
B = np.array([[1, 2], [5, 6], [8, 9]])

In [75]:
A.dot(B)

array([[ 35,  41],
       [ 91, 109],
       [147, 177]])

In [76]:
B.T

array([[1, 5, 8],
       [2, 6, 9]])

In [77]:
B.T @ A

array([[ 98, 112, 126],
       [113, 130, 147]])

## Dot Product Example

In [78]:
np.random.seed(0)
sales_amount = np.random.randint(20, size = (7, 3))

In [79]:
sales_amount

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7],
       [14, 17,  5],
       [13,  8,  9]])

In [80]:
import pandas as pd
weekly_sales = pd.DataFrame(sales_amount, index = ["Mon", "Tues", "Wed", "Thurs", "Fri", "Sat", "Sun"],
                                          columns = ["Almond Butter", "Peanut Butter", "Cashew Butter"])

In [81]:
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7
Sat               14             17              5
Sun               13              8              9